Enhancment in copy operation
ltouati/vfs-gcs pull request #11
Opened 2019-05-27 09:08 UTC by ashokmor

Override canRenameTo method, now it returns false to check possibilities server side copy
Override copyFrom method to use blob copy operation if blob is being moved or copied to same gcs project
This has improved file operation of big file size within same storage account

2019-07-24 11:30 UTC, ashokmor commented
@ltouati 

Could you review PR please, have added following features

Added server side copy, Copying file from GCS to GCS would get benefited as they no longer need to streams and read/write datas.
Generating signed url for GCS location

2019-08-27 10:17 UTC, ashokmor commented
@ltouati  any update? today again I push change to improve it further

2019-10-04 05:33 UTC, ashokmor commented
@ltouati 
 please review PR

2019-10-10 13:26 UTC, ltouati requested changes

2019-10-10 13:26 UTC, ltouati commented on src/main/java/com/celarli/commons/vfs/provider/google/GCSFileObject.java
> +
Remove space

2019-10-10 13:26 UTC, ltouati commented on src/main/java/com/celarli/commons/vfs/provider/google/GCSFileObject.java
> +                e.printStackTrace();
either swallow the exception or log it or rethrow it

2019-10-10 13:26 UTC, ltouati commented on src/main/java/com/celarli/commons/vfs/provider/google/GCSFileObject.java
> +                    try {
can we use try(Closeable) idom instead ?

2019-10-10 13:26 UTC, ltouati commented on src/main/java/com/celarli/commons/vfs/provider/google/GCSFileObject.java
> +
Remove space

2019-10-10 13:26 UTC, ltouati commented on src/main/java/com/celarli/commons/vfs/provider/google/GCSFileObject.java
> +
remove space

2019-10-11 09:23 UTC, ashokmor commented
@ltouati 
Please review, all of PR comment addressed

2019-12-08 08:38 UTC, merged